//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smena
    {
        public int SmenaID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime SmenaDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
