//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int ZakazID { get; set; }
        public Nullable<int> WaiterID { get; set; }
        public Nullable<int> BlydoID { get; set; }
        public string ZakazStatus { get; set; }
        public System.DateTime ZakazDate { get; set; }
    
        public virtual Blydo Blydo { get; set; }
        public virtual Users Users { get; set; }
    }
}
